# NameError
'''
contoh = 'Data'
print(conto)
'''


#Expected an Indented Block
'''
def contoh():
def contoh1():
    print('data')
'''

#Unexpected Indent 
'''
def contoh():
    print('data')
        print('data')
print('data')
'''

#Unexpected EOF 
'''
x = [1,2,3,4,5
def contoh():
''' 
